// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/v2/internal/pool (interfaces: Metrics)

// Package pool is a generated GoMock package.
package pool

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// DeadConnInc mocks base method.
func (m *MockMetrics) DeadConnInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeadConnInc", arg0)
}

// DeadConnInc indicates an expected call of DeadConnInc.
func (mr *MockMetricsMockRecorder) DeadConnInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeadConnInc", reflect.TypeOf((*MockMetrics)(nil).DeadConnInc), arg0)
}

// GetConnInc mocks base method.
func (m *MockMetrics) GetConnInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetConnInc", arg0, arg1)
}

// GetConnInc indicates an expected call of GetConnInc.
func (mr *MockMetricsMockRecorder) GetConnInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnInc", reflect.TypeOf((*MockMetrics)(nil).GetConnInc), arg0, arg1)
}

// LiveConnInc mocks base method.
func (m *MockMetrics) LiveConnInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LiveConnInc", arg0)
}

// LiveConnInc indicates an expected call of LiveConnInc.
func (mr *MockMetricsMockRecorder) LiveConnInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveConnInc", reflect.TypeOf((*MockMetrics)(nil).LiveConnInc), arg0)
}

// NewConnsInc mocks base method.
func (m *MockMetrics) NewConnsInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NewConnsInc", arg0, arg1)
}

// NewConnsInc indicates an expected call of NewConnsInc.
func (mr *MockMetricsMockRecorder) NewConnsInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConnsInc", reflect.TypeOf((*MockMetrics)(nil).NewConnsInc), arg0, arg1)
}

// PutConnInc mocks base method.
func (m *MockMetrics) PutConnInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PutConnInc", arg0, arg1)
}

// PutConnInc indicates an expected call of PutConnInc.
func (mr *MockMetricsMockRecorder) PutConnInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutConnInc", reflect.TypeOf((*MockMetrics)(nil).PutConnInc), arg0, arg1)
}

// RemovedConnsAdd mocks base method.
func (m *MockMetrics) RemovedConnsAdd(arg0 string, arg1 uint) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemovedConnsAdd", arg0, arg1)
}

// RemovedConnsAdd indicates an expected call of RemovedConnsAdd.
func (mr *MockMetricsMockRecorder) RemovedConnsAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovedConnsAdd", reflect.TypeOf((*MockMetrics)(nil).RemovedConnsAdd), arg0, arg1)
}

// RenewConnInc mocks base method.
func (m *MockMetrics) RenewConnInc(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenewConnInc", arg0, arg1, arg2)
}

// RenewConnInc indicates an expected call of RenewConnInc.
func (mr *MockMetricsMockRecorder) RenewConnInc(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewConnInc", reflect.TypeOf((*MockMetrics)(nil).RenewConnInc), arg0, arg1, arg2)
}
