// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/v2/internal/pool (interfaces: Metrics)

// Package pool is a generated GoMock package.
package pool

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// ConnsAdd mocks base method.
func (m *MockMetrics) ConnsAdd(arg0 string, arg1 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConnsAdd", arg0, arg1)
}

// ConnsAdd indicates an expected call of ConnsAdd.
func (mr *MockMetricsMockRecorder) ConnsAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnsAdd", reflect.TypeOf((*MockMetrics)(nil).ConnsAdd), arg0, arg1)
}

// InUseConnsAdd mocks base method.
func (m *MockMetrics) InUseConnsAdd(arg0 string, arg1 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InUseConnsAdd", arg0, arg1)
}

// InUseConnsAdd indicates an expected call of InUseConnsAdd.
func (mr *MockMetricsMockRecorder) InUseConnsAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InUseConnsAdd", reflect.TypeOf((*MockMetrics)(nil).InUseConnsAdd), arg0, arg1)
}

// LiveConnsAdd mocks base method.
func (m *MockMetrics) LiveConnsAdd(arg0 string, arg1 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LiveConnsAdd", arg0, arg1)
}

// LiveConnsAdd indicates an expected call of LiveConnsAdd.
func (mr *MockMetricsMockRecorder) LiveConnsAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveConnsAdd", reflect.TypeOf((*MockMetrics)(nil).LiveConnsAdd), arg0, arg1)
}

// RenewRequestsInc mocks base method.
func (m *MockMetrics) RenewRequestsInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenewRequestsInc", arg0)
}

// RenewRequestsInc indicates an expected call of RenewRequestsInc.
func (mr *MockMetricsMockRecorder) RenewRequestsInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewRequestsInc", reflect.TypeOf((*MockMetrics)(nil).RenewRequestsInc), arg0)
}

// RenewalsInc mocks base method.
func (m *MockMetrics) RenewalsInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenewalsInc", arg0)
}

// RenewalsInc indicates an expected call of RenewalsInc.
func (mr *MockMetricsMockRecorder) RenewalsInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewalsInc", reflect.TypeOf((*MockMetrics)(nil).RenewalsInc), arg0)
}
