// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/v2/internal/pool (interfaces: Metrics)

// Package pool is a generated GoMock package.
package pool

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// DeadConnsInc mocks base method.
func (m *MockMetrics) DeadConnsInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeadConnsInc", arg0)
}

// DeadConnsInc indicates an expected call of DeadConnsInc.
func (mr *MockMetricsMockRecorder) DeadConnsInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeadConnsInc", reflect.TypeOf((*MockMetrics)(nil).DeadConnsInc), arg0)
}

// GetConnsInc mocks base method.
func (m *MockMetrics) GetConnsInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetConnsInc", arg0, arg1)
}

// GetConnsInc indicates an expected call of GetConnsInc.
func (mr *MockMetricsMockRecorder) GetConnsInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnsInc", reflect.TypeOf((*MockMetrics)(nil).GetConnsInc), arg0, arg1)
}

// NewConnsInc mocks base method.
func (m *MockMetrics) NewConnsInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NewConnsInc", arg0, arg1)
}

// NewConnsInc indicates an expected call of NewConnsInc.
func (mr *MockMetricsMockRecorder) NewConnsInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConnsInc", reflect.TypeOf((*MockMetrics)(nil).NewConnsInc), arg0, arg1)
}

// PutConnsInc mocks base method.
func (m *MockMetrics) PutConnsInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PutConnsInc", arg0, arg1)
}

// PutConnsInc indicates an expected call of PutConnsInc.
func (mr *MockMetricsMockRecorder) PutConnsInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutConnsInc", reflect.TypeOf((*MockMetrics)(nil).PutConnsInc), arg0, arg1)
}

// RemovedConnsAdd mocks base method.
func (m *MockMetrics) RemovedConnsAdd(arg0 string, arg1 uint) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemovedConnsAdd", arg0, arg1)
}

// RemovedConnsAdd indicates an expected call of RemovedConnsAdd.
func (mr *MockMetricsMockRecorder) RemovedConnsAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovedConnsAdd", reflect.TypeOf((*MockMetrics)(nil).RemovedConnsAdd), arg0, arg1)
}

// RenewedConnsInc mocks base method.
func (m *MockMetrics) RenewedConnsInc(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenewedConnsInc", arg0, arg1, arg2)
}

// RenewedConnsInc indicates an expected call of RenewedConnsInc.
func (mr *MockMetricsMockRecorder) RenewedConnsInc(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewedConnsInc", reflect.TypeOf((*MockMetrics)(nil).RenewedConnsInc), arg0, arg1, arg2)
}
