// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/v2/pkg/middlewares/log/format (interfaces: Interface)

// Package log is a generated GoMock package.
package log

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dns "github.com/miekg/dns"
)

// MockFormat is a mock of Interface interface.
type MockFormat struct {
	ctrl     *gomock.Controller
	recorder *MockFormatMockRecorder
}

// MockFormatMockRecorder is the mock recorder for MockFormat.
type MockFormatMockRecorder struct {
	mock *MockFormat
}

// NewMockFormat creates a new mock instance.
func NewMockFormat(ctrl *gomock.Controller) *MockFormat {
	mock := &MockFormat{ctrl: ctrl}
	mock.recorder = &MockFormatMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFormat) EXPECT() *MockFormatMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockFormat) Error(arg0 uint16, arg1 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockFormatMockRecorder) Error(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockFormat)(nil).Error), arg0, arg1)
}

// Request mocks base method.
func (m *MockFormat) Request(arg0 *dns.Msg) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockFormatMockRecorder) Request(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockFormat)(nil).Request), arg0)
}

// RequestResponse mocks base method.
func (m *MockFormat) RequestResponse(arg0, arg1 *dns.Msg) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestResponse", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// RequestResponse indicates an expected call of RequestResponse.
func (mr *MockFormatMockRecorder) RequestResponse(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestResponse", reflect.TypeOf((*MockFormat)(nil).RequestResponse), arg0, arg1)
}

// Response mocks base method.
func (m *MockFormat) Response(arg0 *dns.Msg) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Response", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// Response indicates an expected call of Response.
func (mr *MockFormatMockRecorder) Response(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Response", reflect.TypeOf((*MockFormat)(nil).Response), arg0)
}
