// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/v2/pkg/middlewares/log (interfaces: Logger)
//
// Generated by this command:
//
//	mockgen -write_package_comment=false -destination=mocks_test.go -package log . Logger
//

package log

import (
	net "net"
	reflect "reflect"

	dns "github.com/miekg/dns"
	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockLogger) Error(id uint16, errorString string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", id, errorString)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(id, errorString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), id, errorString)
}

// Log mocks base method.
func (m *MockLogger) Log(remoteAddr net.Addr, request, response *dns.Msg) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Log", remoteAddr, request, response)
}

// Log indicates an expected call of Log.
func (mr *MockLoggerMockRecorder) Log(remoteAddr, request, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockLogger)(nil).Log), remoteAddr, request, response)
}
