# Temporary status
- name: "🗯️ Waiting for feedback"
  color: "aadefa"
- name: "🔴 Blocked"
  color: "ff3f14"
  description: "Blocked by another issue or pull request"
- name: "🔒 After next release"
  color: "e8f274"

# Priority
- name: "🚨 Urgent"
  color: "d5232f"
- name: "💤 Low priority"
  color: "4285f4"

# Complexity
- name: "☣️ Hard to do"
  color: "7d0008"
- name: "🟩 Easy to do"
  color: "34cf43"

# Problem category
- name: "Config problem"
  color: "ffc7ea"
- name: "Documentation"
  color: "ffc7ea"
- name: "DNS over TLS"
  color: "ffc7ea"
- name: "DNS over HTTPS"
  color: "ffc7ea"
- name: "Metrics"
  color: "ffc7ea"
- name: "Logging"
  color: "ffc7ea"
- name: "Healthcheck"
  color: "ffc7ea"
- name: "Filter"
  color: "ffc7ea"
- name: "Go code library"
  color: "ffc7ea"
