version: "2"
linters:
  settings:
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
        path: _test\.go
      - linters:
          - dupl
        path: pkg/provider/.*\.go
      - linters:
          - dupl
        path: internal/config/.*\.go
      - linters:
          - lll
        source: ^\t+(defaultPlainIPv6AddrPort|defaultDoTIPv6AddrPort|netip.AddrFrom16)\(.+\),$
      - linters:
          - ireturn
        text: .+returns interface \(github\.com\/prometheus\/client_golang\/prometheus\.[a-zA-Z]+\)$
      - linters:
          - nolintlint
        path: pkg/middlewares/.+/middleware\.go
        text: directive `\/\/nolint:ireturn` is unused for linter "ireturn"
      - linters:
          - goconst
        path: pkg/(plain|dot|doh)/.+\.go
        text: string `ipv6` has 3 occurrences, make it a constant
    paths:
      - third_party$
      - builtin$
      - examples$
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
