// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/v2/pkg/server (interfaces: Dialer,PoolMetrics,Logger,Middleware)

// Package server is a generated GoMock package.
package server

import (
	context "context"
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dns "github.com/miekg/dns"
)

// MockDialer is a mock of Dialer interface.
type MockDialer struct {
	ctrl     *gomock.Controller
	recorder *MockDialerMockRecorder
}

// MockDialerMockRecorder is the mock recorder for MockDialer.
type MockDialerMockRecorder struct {
	mock *MockDialer
}

// NewMockDialer creates a new mock instance.
func NewMockDialer(ctrl *gomock.Controller) *MockDialer {
	mock := &MockDialer{ctrl: ctrl}
	mock.recorder = &MockDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialer) EXPECT() *MockDialerMockRecorder {
	return m.recorder
}

// Addresses mocks base method.
func (m *MockDialer) Addresses() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Addresses")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Addresses indicates an expected call of Addresses.
func (mr *MockDialerMockRecorder) Addresses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Addresses", reflect.TypeOf((*MockDialer)(nil).Addresses))
}

// Dial mocks base method.
func (m *MockDialer) Dial(arg0 context.Context, arg1, arg2 string) (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", arg0, arg1, arg2)
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial.
func (mr *MockDialerMockRecorder) Dial(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockDialer)(nil).Dial), arg0, arg1, arg2)
}

// ReusableConnsSupported mocks base method.
func (m *MockDialer) ReusableConnsSupported() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReusableConnsSupported")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReusableConnsSupported indicates an expected call of ReusableConnsSupported.
func (mr *MockDialerMockRecorder) ReusableConnsSupported() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReusableConnsSupported", reflect.TypeOf((*MockDialer)(nil).ReusableConnsSupported))
}

// String mocks base method.
func (m *MockDialer) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockDialerMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockDialer)(nil).String))
}

// MockPoolMetrics is a mock of PoolMetrics interface.
type MockPoolMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockPoolMetricsMockRecorder
}

// MockPoolMetricsMockRecorder is the mock recorder for MockPoolMetrics.
type MockPoolMetricsMockRecorder struct {
	mock *MockPoolMetrics
}

// NewMockPoolMetrics creates a new mock instance.
func NewMockPoolMetrics(ctrl *gomock.Controller) *MockPoolMetrics {
	mock := &MockPoolMetrics{ctrl: ctrl}
	mock.recorder = &MockPoolMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoolMetrics) EXPECT() *MockPoolMetricsMockRecorder {
	return m.recorder
}

// ConnsAdd mocks base method.
func (m *MockPoolMetrics) ConnsAdd(arg0 string, arg1 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConnsAdd", arg0, arg1)
}

// ConnsAdd indicates an expected call of ConnsAdd.
func (mr *MockPoolMetricsMockRecorder) ConnsAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnsAdd", reflect.TypeOf((*MockPoolMetrics)(nil).ConnsAdd), arg0, arg1)
}

// InUseConnsAdd mocks base method.
func (m *MockPoolMetrics) InUseConnsAdd(arg0 string, arg1 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InUseConnsAdd", arg0, arg1)
}

// InUseConnsAdd indicates an expected call of InUseConnsAdd.
func (mr *MockPoolMetricsMockRecorder) InUseConnsAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InUseConnsAdd", reflect.TypeOf((*MockPoolMetrics)(nil).InUseConnsAdd), arg0, arg1)
}

// LiveConnsAdd mocks base method.
func (m *MockPoolMetrics) LiveConnsAdd(arg0 string, arg1 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LiveConnsAdd", arg0, arg1)
}

// LiveConnsAdd indicates an expected call of LiveConnsAdd.
func (mr *MockPoolMetricsMockRecorder) LiveConnsAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveConnsAdd", reflect.TypeOf((*MockPoolMetrics)(nil).LiveConnsAdd), arg0, arg1)
}

// RenewRequestsInc mocks base method.
func (m *MockPoolMetrics) RenewRequestsInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenewRequestsInc", arg0)
}

// RenewRequestsInc indicates an expected call of RenewRequestsInc.
func (mr *MockPoolMetricsMockRecorder) RenewRequestsInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewRequestsInc", reflect.TypeOf((*MockPoolMetrics)(nil).RenewRequestsInc), arg0)
}

// RenewalsInc mocks base method.
func (m *MockPoolMetrics) RenewalsInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenewalsInc", arg0)
}

// RenewalsInc indicates an expected call of RenewalsInc.
func (mr *MockPoolMetricsMockRecorder) RenewalsInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewalsInc", reflect.TypeOf((*MockPoolMetrics)(nil).RenewalsInc), arg0)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", arg0)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), arg0)
}

// Info mocks base method.
func (m *MockLogger) Info(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", arg0)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), arg0)
}

// Warn mocks base method.
func (m *MockLogger) Warn(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", arg0)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), arg0)
}

// MockMiddleware is a mock of Middleware interface.
type MockMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockMiddlewareMockRecorder
}

// MockMiddlewareMockRecorder is the mock recorder for MockMiddleware.
type MockMiddlewareMockRecorder struct {
	mock *MockMiddleware
}

// NewMockMiddleware creates a new mock instance.
func NewMockMiddleware(ctrl *gomock.Controller) *MockMiddleware {
	mock := &MockMiddleware{ctrl: ctrl}
	mock.recorder = &MockMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiddleware) EXPECT() *MockMiddlewareMockRecorder {
	return m.recorder
}

// Stop mocks base method.
func (m *MockMiddleware) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockMiddlewareMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockMiddleware)(nil).Stop))
}

// String mocks base method.
func (m *MockMiddleware) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockMiddlewareMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockMiddleware)(nil).String))
}

// Wrap mocks base method.
func (m *MockMiddleware) Wrap(arg0 dns.Handler) dns.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wrap", arg0)
	ret0, _ := ret[0].(dns.Handler)
	return ret0
}

// Wrap indicates an expected call of Wrap.
func (mr *MockMiddlewareMockRecorder) Wrap(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wrap", reflect.TypeOf((*MockMiddleware)(nil).Wrap), arg0)
}
