// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/v2/pkg/server (interfaces: Dialer,PoolMetrics,Logger,Middleware)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package server . Dialer,PoolMetrics,Logger,Middleware
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	net "net"
	reflect "reflect"
	time "time"

	dns "github.com/miekg/dns"
	gomock "go.uber.org/mock/gomock"
)

// MockDialer is a mock of Dialer interface.
type MockDialer struct {
	ctrl     *gomock.Controller
	recorder *MockDialerMockRecorder
	isgomock struct{}
}

// MockDialerMockRecorder is the mock recorder for MockDialer.
type MockDialerMockRecorder struct {
	mock *MockDialer
}

// NewMockDialer creates a new mock instance.
func NewMockDialer(ctrl *gomock.Controller) *MockDialer {
	mock := &MockDialer{ctrl: ctrl}
	mock.recorder = &MockDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialer) EXPECT() *MockDialerMockRecorder {
	return m.recorder
}

// Addresses mocks base method.
func (m *MockDialer) Addresses() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Addresses")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Addresses indicates an expected call of Addresses.
func (mr *MockDialerMockRecorder) Addresses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Addresses", reflect.TypeOf((*MockDialer)(nil).Addresses))
}

// Dial mocks base method.
func (m *MockDialer) Dial(ctx context.Context, network, arg2 string) (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", ctx, network, arg2)
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial.
func (mr *MockDialerMockRecorder) Dial(ctx, network, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockDialer)(nil).Dial), ctx, network, arg2)
}

// ReusableConnsSupported mocks base method.
func (m *MockDialer) ReusableConnsSupported() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReusableConnsSupported")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReusableConnsSupported indicates an expected call of ReusableConnsSupported.
func (mr *MockDialerMockRecorder) ReusableConnsSupported() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReusableConnsSupported", reflect.TypeOf((*MockDialer)(nil).ReusableConnsSupported))
}

// String mocks base method.
func (m *MockDialer) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockDialerMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockDialer)(nil).String))
}

// MockPoolMetrics is a mock of PoolMetrics interface.
type MockPoolMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockPoolMetricsMockRecorder
	isgomock struct{}
}

// MockPoolMetricsMockRecorder is the mock recorder for MockPoolMetrics.
type MockPoolMetricsMockRecorder struct {
	mock *MockPoolMetrics
}

// NewMockPoolMetrics creates a new mock instance.
func NewMockPoolMetrics(ctrl *gomock.Controller) *MockPoolMetrics {
	mock := &MockPoolMetrics{ctrl: ctrl}
	mock.recorder = &MockPoolMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoolMetrics) EXPECT() *MockPoolMetricsMockRecorder {
	return m.recorder
}

// DeadConnInc mocks base method.
func (m *MockPoolMetrics) DeadConnInc(address string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeadConnInc", address)
}

// DeadConnInc indicates an expected call of DeadConnInc.
func (mr *MockPoolMetricsMockRecorder) DeadConnInc(address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeadConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).DeadConnInc), address)
}

// GetConnInc mocks base method.
func (m *MockPoolMetrics) GetConnInc(address, outcome string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetConnInc", address, outcome)
}

// GetConnInc indicates an expected call of GetConnInc.
func (mr *MockPoolMetricsMockRecorder) GetConnInc(address, outcome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).GetConnInc), address, outcome)
}

// LiveConnInc mocks base method.
func (m *MockPoolMetrics) LiveConnInc(address string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LiveConnInc", address)
}

// LiveConnInc indicates an expected call of LiveConnInc.
func (mr *MockPoolMetricsMockRecorder) LiveConnInc(address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).LiveConnInc), address)
}

// NewConnsInc mocks base method.
func (m *MockPoolMetrics) NewConnsInc(address, outcome string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NewConnsInc", address, outcome)
}

// NewConnsInc indicates an expected call of NewConnsInc.
func (mr *MockPoolMetricsMockRecorder) NewConnsInc(address, outcome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConnsInc", reflect.TypeOf((*MockPoolMetrics)(nil).NewConnsInc), address, outcome)
}

// PutConnInc mocks base method.
func (m *MockPoolMetrics) PutConnInc(address, state string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PutConnInc", address, state)
}

// PutConnInc indicates an expected call of PutConnInc.
func (mr *MockPoolMetricsMockRecorder) PutConnInc(address, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).PutConnInc), address, state)
}

// RecordLifetime mocks base method.
func (m *MockPoolMetrics) RecordLifetime(address string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordLifetime", address, duration)
}

// RecordLifetime indicates an expected call of RecordLifetime.
func (mr *MockPoolMetricsMockRecorder) RecordLifetime(address, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordLifetime", reflect.TypeOf((*MockPoolMetrics)(nil).RecordLifetime), address, duration)
}

// RecordUseTime mocks base method.
func (m *MockPoolMetrics) RecordUseTime(address string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordUseTime", address, duration)
}

// RecordUseTime indicates an expected call of RecordUseTime.
func (mr *MockPoolMetricsMockRecorder) RecordUseTime(address, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordUseTime", reflect.TypeOf((*MockPoolMetrics)(nil).RecordUseTime), address, duration)
}

// RemovedConnsAdd mocks base method.
func (m *MockPoolMetrics) RemovedConnsAdd(address string, removed uint) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemovedConnsAdd", address, removed)
}

// RemovedConnsAdd indicates an expected call of RemovedConnsAdd.
func (mr *MockPoolMetricsMockRecorder) RemovedConnsAdd(address, removed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovedConnsAdd", reflect.TypeOf((*MockPoolMetrics)(nil).RemovedConnsAdd), address, removed)
}

// RenewConnInc mocks base method.
func (m *MockPoolMetrics) RenewConnInc(address, reason, outcome string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenewConnInc", address, reason, outcome)
}

// RenewConnInc indicates an expected call of RenewConnInc.
func (mr *MockPoolMetricsMockRecorder) RenewConnInc(address, reason, outcome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).RenewConnInc), address, reason, outcome)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", s)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), s)
}

// Info mocks base method.
func (m *MockLogger) Info(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", s)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), s)
}

// Warn mocks base method.
func (m *MockLogger) Warn(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", s)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), s)
}

// MockMiddleware is a mock of Middleware interface.
type MockMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockMiddlewareMockRecorder
	isgomock struct{}
}

// MockMiddlewareMockRecorder is the mock recorder for MockMiddleware.
type MockMiddlewareMockRecorder struct {
	mock *MockMiddleware
}

// NewMockMiddleware creates a new mock instance.
func NewMockMiddleware(ctrl *gomock.Controller) *MockMiddleware {
	mock := &MockMiddleware{ctrl: ctrl}
	mock.recorder = &MockMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiddleware) EXPECT() *MockMiddlewareMockRecorder {
	return m.recorder
}

// Stop mocks base method.
func (m *MockMiddleware) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockMiddlewareMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockMiddleware)(nil).Stop))
}

// String mocks base method.
func (m *MockMiddleware) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockMiddlewareMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockMiddleware)(nil).String))
}

// Wrap mocks base method.
func (m *MockMiddleware) Wrap(next dns.Handler) dns.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wrap", next)
	ret0, _ := ret[0].(dns.Handler)
	return ret0
}

// Wrap indicates an expected call of Wrap.
func (mr *MockMiddlewareMockRecorder) Wrap(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wrap", reflect.TypeOf((*MockMiddleware)(nil).Wrap), next)
}
