// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces_local.go
//
// Generated by this command:
//
//	mockgen -destination=mocks_local_test.go -package server -source interfaces_local.go
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	dns "github.com/miekg/dns"
	gomock "go.uber.org/mock/gomock"
)

// MockexchangerIntf is a mock of exchangerIntf interface.
type MockexchangerIntf struct {
	ctrl     *gomock.Controller
	recorder *MockexchangerIntfMockRecorder
	isgomock struct{}
}

// MockexchangerIntfMockRecorder is the mock recorder for MockexchangerIntf.
type MockexchangerIntfMockRecorder struct {
	mock *MockexchangerIntf
}

// NewMockexchangerIntf creates a new mock instance.
func NewMockexchangerIntf(ctrl *gomock.Controller) *MockexchangerIntf {
	mock := &MockexchangerIntf{ctrl: ctrl}
	mock.recorder = &MockexchangerIntfMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexchangerIntf) EXPECT() *MockexchangerIntfMockRecorder {
	return m.recorder
}

// Exchange mocks base method.
func (m *MockexchangerIntf) Exchange(ctx context.Context, network string, request *dns.Msg) (*dns.Msg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exchange", ctx, network, request)
	ret0, _ := ret[0].(*dns.Msg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exchange indicates an expected call of Exchange.
func (mr *MockexchangerIntfMockRecorder) Exchange(ctx, network, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exchange", reflect.TypeOf((*MockexchangerIntf)(nil).Exchange), ctx, network, request)
}
