// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/v2/pkg/middlewares/localdns (interfaces: LocalChecker,Logger)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package localdns . LocalChecker,Logger
//

// Package localdns is a generated GoMock package.
package localdns

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLocalChecker is a mock of LocalChecker interface.
type MockLocalChecker struct {
	ctrl     *gomock.Controller
	recorder *MockLocalCheckerMockRecorder
	isgomock struct{}
}

// MockLocalCheckerMockRecorder is the mock recorder for MockLocalChecker.
type MockLocalCheckerMockRecorder struct {
	mock *MockLocalChecker
}

// NewMockLocalChecker creates a new mock instance.
func NewMockLocalChecker(ctrl *gomock.Controller) *MockLocalChecker {
	mock := &MockLocalChecker{ctrl: ctrl}
	mock.recorder = &MockLocalCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalChecker) EXPECT() *MockLocalCheckerMockRecorder {
	return m.recorder
}

// IsFQDNLocal mocks base method.
func (m *MockLocalChecker) IsFQDNLocal(fqdn string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFQDNLocal", fqdn)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFQDNLocal indicates an expected call of IsFQDNLocal.
func (mr *MockLocalCheckerMockRecorder) IsFQDNLocal(fqdn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFQDNLocal", reflect.TypeOf((*MockLocalChecker)(nil).IsFQDNLocal), fqdn)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", message)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), message)
}

// Warn mocks base method.
func (m *MockLogger) Warn(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", message)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), message)
}
