// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces_test.go

// Package dot is a generated GoMock package.
package dot

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dns "github.com/miekg/dns"
	update "github.com/qdm12/dns/v2/pkg/filter/update"
)

// MockmiddlewareMetrics is a mock of middlewareMetrics interface.
type MockmiddlewareMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockmiddlewareMetricsMockRecorder
}

// MockmiddlewareMetricsMockRecorder is the mock recorder for MockmiddlewareMetrics.
type MockmiddlewareMetricsMockRecorder struct {
	mock *MockmiddlewareMetrics
}

// NewMockmiddlewareMetrics creates a new mock instance.
func NewMockmiddlewareMetrics(ctrl *gomock.Controller) *MockmiddlewareMetrics {
	mock := &MockmiddlewareMetrics{ctrl: ctrl}
	mock.recorder = &MockmiddlewareMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmiddlewareMetrics) EXPECT() *MockmiddlewareMetricsMockRecorder {
	return m.recorder
}

// AnswersInc mocks base method.
func (m *MockmiddlewareMetrics) AnswersInc(class, qType string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AnswersInc", class, qType)
}

// AnswersInc indicates an expected call of AnswersInc.
func (mr *MockmiddlewareMetricsMockRecorder) AnswersInc(class, qType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswersInc", reflect.TypeOf((*MockmiddlewareMetrics)(nil).AnswersInc), class, qType)
}

// InFlightRequestsDec mocks base method.
func (m *MockmiddlewareMetrics) InFlightRequestsDec() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InFlightRequestsDec")
}

// InFlightRequestsDec indicates an expected call of InFlightRequestsDec.
func (mr *MockmiddlewareMetricsMockRecorder) InFlightRequestsDec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InFlightRequestsDec", reflect.TypeOf((*MockmiddlewareMetrics)(nil).InFlightRequestsDec))
}

// InFlightRequestsInc mocks base method.
func (m *MockmiddlewareMetrics) InFlightRequestsInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InFlightRequestsInc")
}

// InFlightRequestsInc indicates an expected call of InFlightRequestsInc.
func (mr *MockmiddlewareMetricsMockRecorder) InFlightRequestsInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InFlightRequestsInc", reflect.TypeOf((*MockmiddlewareMetrics)(nil).InFlightRequestsInc))
}

// QuestionsInc mocks base method.
func (m *MockmiddlewareMetrics) QuestionsInc(class, qType string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QuestionsInc", class, qType)
}

// QuestionsInc indicates an expected call of QuestionsInc.
func (mr *MockmiddlewareMetricsMockRecorder) QuestionsInc(class, qType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuestionsInc", reflect.TypeOf((*MockmiddlewareMetrics)(nil).QuestionsInc), class, qType)
}

// RcodeInc mocks base method.
func (m *MockmiddlewareMetrics) RcodeInc(rcode string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RcodeInc", rcode)
}

// RcodeInc indicates an expected call of RcodeInc.
func (mr *MockmiddlewareMetricsMockRecorder) RcodeInc(rcode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RcodeInc", reflect.TypeOf((*MockmiddlewareMetrics)(nil).RcodeInc), rcode)
}

// RequestsInc mocks base method.
func (m *MockmiddlewareMetrics) RequestsInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RequestsInc")
}

// RequestsInc indicates an expected call of RequestsInc.
func (mr *MockmiddlewareMetricsMockRecorder) RequestsInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestsInc", reflect.TypeOf((*MockmiddlewareMetrics)(nil).RequestsInc))
}

// ResponsesInc mocks base method.
func (m *MockmiddlewareMetrics) ResponsesInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResponsesInc")
}

// ResponsesInc indicates an expected call of ResponsesInc.
func (mr *MockmiddlewareMetricsMockRecorder) ResponsesInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponsesInc", reflect.TypeOf((*MockmiddlewareMetrics)(nil).ResponsesInc))
}

// Mockfilter is a mock of filter interface.
type Mockfilter struct {
	ctrl     *gomock.Controller
	recorder *MockfilterMockRecorder
}

// MockfilterMockRecorder is the mock recorder for Mockfilter.
type MockfilterMockRecorder struct {
	mock *Mockfilter
}

// NewMockfilter creates a new mock instance.
func NewMockfilter(ctrl *gomock.Controller) *Mockfilter {
	mock := &Mockfilter{ctrl: ctrl}
	mock.recorder = &MockfilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockfilter) EXPECT() *MockfilterMockRecorder {
	return m.recorder
}

// FilterRequest mocks base method.
func (m *Mockfilter) FilterRequest(request *dns.Msg) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterRequest", request)
	ret0, _ := ret[0].(bool)
	return ret0
}

// FilterRequest indicates an expected call of FilterRequest.
func (mr *MockfilterMockRecorder) FilterRequest(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterRequest", reflect.TypeOf((*Mockfilter)(nil).FilterRequest), request)
}

// FilterResponse mocks base method.
func (m *Mockfilter) FilterResponse(response *dns.Msg) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterResponse", response)
	ret0, _ := ret[0].(bool)
	return ret0
}

// FilterResponse indicates an expected call of FilterResponse.
func (mr *MockfilterMockRecorder) FilterResponse(response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterResponse", reflect.TypeOf((*Mockfilter)(nil).FilterResponse), response)
}

// Update mocks base method.
func (m *Mockfilter) Update(settings update.Settings) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", settings)
}

// Update indicates an expected call of Update.
func (mr *MockfilterMockRecorder) Update(settings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*Mockfilter)(nil).Update), settings)
}

// Mockcache is a mock of cache interface.
type Mockcache struct {
	ctrl     *gomock.Controller
	recorder *MockcacheMockRecorder
}

// MockcacheMockRecorder is the mock recorder for Mockcache.
type MockcacheMockRecorder struct {
	mock *Mockcache
}

// NewMockcache creates a new mock instance.
func NewMockcache(ctrl *gomock.Controller) *Mockcache {
	mock := &Mockcache{ctrl: ctrl}
	mock.recorder = &MockcacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcache) EXPECT() *MockcacheMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *Mockcache) Add(request, response *dns.Msg) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", request, response)
}

// Add indicates an expected call of Add.
func (mr *MockcacheMockRecorder) Add(request, response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*Mockcache)(nil).Add), request, response)
}

// Get mocks base method.
func (m *Mockcache) Get(request *dns.Msg) *dns.Msg {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", request)
	ret0, _ := ret[0].(*dns.Msg)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockcacheMockRecorder) Get(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockcache)(nil).Get), request)
}
