// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/v2/internal/picker (interfaces: Interface)

// Package dot is a generated GoMock package.
package dot

import (
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	provider "github.com/qdm12/dns/v2/pkg/provider"
)

// MockPicker is a mock of Interface interface.
type MockPicker struct {
	ctrl     *gomock.Controller
	recorder *MockPickerMockRecorder
}

// MockPickerMockRecorder is the mock recorder for MockPicker.
type MockPickerMockRecorder struct {
	mock *MockPicker
}

// NewMockPicker creates a new mock instance.
func NewMockPicker(ctrl *gomock.Controller) *MockPicker {
	mock := &MockPicker{ctrl: ctrl}
	mock.recorder = &MockPickerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPicker) EXPECT() *MockPickerMockRecorder {
	return m.recorder
}

// DNSIP mocks base method.
func (m *MockPicker) DNSIP(arg0 provider.DNSServer, arg1 bool) net.IP {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DNSIP", arg0, arg1)
	ret0, _ := ret[0].(net.IP)
	return ret0
}

// DNSIP indicates an expected call of DNSIP.
func (mr *MockPickerMockRecorder) DNSIP(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DNSIP", reflect.TypeOf((*MockPicker)(nil).DNSIP), arg0, arg1)
}

// DNSServer mocks base method.
func (m *MockPicker) DNSServer(arg0 []provider.DNSServer) provider.DNSServer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DNSServer", arg0)
	ret0, _ := ret[0].(provider.DNSServer)
	return ret0
}

// DNSServer indicates an expected call of DNSServer.
func (mr *MockPickerMockRecorder) DNSServer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DNSServer", reflect.TypeOf((*MockPicker)(nil).DNSServer), arg0)
}

// DoTIP mocks base method.
func (m *MockPicker) DoTIP(arg0 provider.DoTServer, arg1 bool) net.IP {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoTIP", arg0, arg1)
	ret0, _ := ret[0].(net.IP)
	return ret0
}

// DoTIP indicates an expected call of DoTIP.
func (mr *MockPickerMockRecorder) DoTIP(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoTIP", reflect.TypeOf((*MockPicker)(nil).DoTIP), arg0, arg1)
}

// DoTServer mocks base method.
func (m *MockPicker) DoTServer(arg0 []provider.DoTServer) provider.DoTServer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoTServer", arg0)
	ret0, _ := ret[0].(provider.DoTServer)
	return ret0
}

// DoTServer indicates an expected call of DoTServer.
func (mr *MockPickerMockRecorder) DoTServer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoTServer", reflect.TypeOf((*MockPicker)(nil).DoTServer), arg0)
}

// IP mocks base method.
func (m *MockPicker) IP(arg0 []net.IP) net.IP {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IP", arg0)
	ret0, _ := ret[0].(net.IP)
	return ret0
}

// IP indicates an expected call of IP.
func (mr *MockPickerMockRecorder) IP(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IP", reflect.TypeOf((*MockPicker)(nil).IP), arg0)
}
