// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/pkg/dot/metrics (interfaces: Interface)

// Package dot is a generated GoMock package.
package dot

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDoTMetrics is a mock of Interface interface.
type MockDoTMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockDoTMetricsMockRecorder
}

// MockDoTMetricsMockRecorder is the mock recorder for MockDoTMetrics.
type MockDoTMetricsMockRecorder struct {
	mock *MockDoTMetrics
}

// NewMockDoTMetrics creates a new mock instance.
func NewMockDoTMetrics(ctrl *gomock.Controller) *MockDoTMetrics {
	mock := &MockDoTMetrics{ctrl: ctrl}
	mock.recorder = &MockDoTMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDoTMetrics) EXPECT() *MockDoTMetricsMockRecorder {
	return m.recorder
}

// AnswersInc mocks base method.
func (m *MockDoTMetrics) AnswersInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AnswersInc", arg0, arg1)
}

// AnswersInc indicates an expected call of AnswersInc.
func (mr *MockDoTMetricsMockRecorder) AnswersInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswersInc", reflect.TypeOf((*MockDoTMetrics)(nil).AnswersInc), arg0, arg1)
}

// DNSDialInc mocks base method.
func (m *MockDoTMetrics) DNSDialInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DNSDialInc", arg0, arg1)
}

// DNSDialInc indicates an expected call of DNSDialInc.
func (mr *MockDoTMetricsMockRecorder) DNSDialInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DNSDialInc", reflect.TypeOf((*MockDoTMetrics)(nil).DNSDialInc), arg0, arg1)
}

// DoTDialInc mocks base method.
func (m *MockDoTMetrics) DoTDialInc(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DoTDialInc", arg0, arg1, arg2)
}

// DoTDialInc indicates an expected call of DoTDialInc.
func (mr *MockDoTMetricsMockRecorder) DoTDialInc(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoTDialInc", reflect.TypeOf((*MockDoTMetrics)(nil).DoTDialInc), arg0, arg1, arg2)
}

// InFlightRequestsDec mocks base method.
func (m *MockDoTMetrics) InFlightRequestsDec() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InFlightRequestsDec")
}

// InFlightRequestsDec indicates an expected call of InFlightRequestsDec.
func (mr *MockDoTMetricsMockRecorder) InFlightRequestsDec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InFlightRequestsDec", reflect.TypeOf((*MockDoTMetrics)(nil).InFlightRequestsDec))
}

// InFlightRequestsInc mocks base method.
func (m *MockDoTMetrics) InFlightRequestsInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InFlightRequestsInc")
}

// InFlightRequestsInc indicates an expected call of InFlightRequestsInc.
func (mr *MockDoTMetricsMockRecorder) InFlightRequestsInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InFlightRequestsInc", reflect.TypeOf((*MockDoTMetrics)(nil).InFlightRequestsInc))
}

// QuestionsInc mocks base method.
func (m *MockDoTMetrics) QuestionsInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QuestionsInc", arg0, arg1)
}

// QuestionsInc indicates an expected call of QuestionsInc.
func (mr *MockDoTMetricsMockRecorder) QuestionsInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuestionsInc", reflect.TypeOf((*MockDoTMetrics)(nil).QuestionsInc), arg0, arg1)
}

// RcodeInc mocks base method.
func (m *MockDoTMetrics) RcodeInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RcodeInc", arg0)
}

// RcodeInc indicates an expected call of RcodeInc.
func (mr *MockDoTMetricsMockRecorder) RcodeInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RcodeInc", reflect.TypeOf((*MockDoTMetrics)(nil).RcodeInc), arg0)
}

// RequestsInc mocks base method.
func (m *MockDoTMetrics) RequestsInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RequestsInc")
}

// RequestsInc indicates an expected call of RequestsInc.
func (mr *MockDoTMetricsMockRecorder) RequestsInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestsInc", reflect.TypeOf((*MockDoTMetrics)(nil).RequestsInc))
}

// ResponsesInc mocks base method.
func (m *MockDoTMetrics) ResponsesInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResponsesInc")
}

// ResponsesInc indicates an expected call of ResponsesInc.
func (mr *MockDoTMetricsMockRecorder) ResponsesInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponsesInc", reflect.TypeOf((*MockDoTMetrics)(nil).ResponsesInc))
}
