{
 "title": "DNS",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "subsystem", "query": "dns" },
   { "name": "period", "label": "Rate period in seconds", "query": "60,10,1" }
  ]
 },
 "panels": [
  {
   "title": "Requests served",
   "type": "stat",
   "description": "Total number of requests handled by the DNS server since program start",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "${subsystem}_responses_sent" }
   ]
  },
  {
   "title": "DNS over TLS dials",
   "type": "stat",
   "description": "Total number of DNS over TLS dials made since program start",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(dns_dns_over_tls_dials)" }
   ]
  },
  {
   "title": "DNS over HTTPs dials",
   "type": "stat",
   "description": "Total number of DNS over HTTPs dials made since program start",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(dns_dns_over_https_dials)" }
   ]
  },
  {
   "title": "Plaintext DNS dials",
   "type": "stat",
   "description": "Total number of plaintext DNS over UDP dials made since program start",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(${subsystem}_plain_dials)" }
   ]
  },
  {
   "title": "DNS cache hits",
   "type": "stat",
   "description": "Total number of DNS cache hits since program start",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "${subsystem}_cache_hit" }
   ]
  },
  {
   "title": "Requests in process",
   "type": "stat",
   "description": "Current number of DNS requests in process in the server. This number is expected to be zero with low loads.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "${subsystem}_requests_inflight" }
   ]
  },
  {
   "title": "Requests blocked",
   "type": "stat",
   "description": "Current number of DNS requests that were blocked by the filter.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(${subsystem}_hostnames_filtered) + sum(${subsystem}_ips_filtered)"
    }
   ]
  },
  { "title": "DNS server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Requests per ${period}s",
   "type": "timeseries",
   "description": "Server requests received per ${period}s with a 2 minutes rate",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "${period}*rate(${subsystem}_requests_received[2m])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Questions per ${period}s by class and type",
   "type": "timeseries",
   "description": "Rate per ${period}s of questions contained in requests to the DNS server, by class and type.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "${period}*sum(rate(${subsystem}_questions_received[2m])) by (class, type)",
     "legendFormat": "{{class}} {{type}}"
    }
   ]
  },
  {
   "title": "Requests in process",
   "type": "timeseries",
   "description": "Number of requests in process in the DNS server. Under low load, this is expected to be zero.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "${subsystem}_requests_inflight", "legendFormat": "Requests in flight" }
   ]
  },
  {
   "title": "Response codes per ${period}s",
   "type": "timeseries",
   "description": "Server response codes per ${period}s with a 2 minutes rate",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "${period}*sum(rate(${subsystem}_response_rcodes[2m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  { "title": "DNS over TLS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "DNS over TLS dials by IP address per ${period}s",
   "type": "timeseries",
   "description": "DNS over TLS dial network calls per ${period}s with a 2 minutes rate, by address and outcome",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${period}*rate(${subsystem}_dns_over_tls_dials[2m])) by (provider, address, outcome)",
     "legendFormat": "{{provider}} {{address}} {{outcome}}"
    }
   ]
  },
  { "title": "DNS over HTTPs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "DNS over HTTPs dials by URL per ${period}s",
   "type": "timeseries",
   "description": "DNS over HTTPs dial network calls per ${period}s with a 2 minutes rate, by URL",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${period}*rate(${subsystem}_dns_over_https_dials[2m])) by (url)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  { "title": "Plain DNS over UDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Plain DNS dials per ${period}s",
   "type": "timeseries",
   "description": "Plain DNS dial network calls per ${period}s with a 2 minutes rate, by provider, address and outcome",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${period}*rate(${subsystem}_plain_dials[2m])) by (address, outcome)",
     "legendFormat": "{{address}} {{outcome}}"
    }
   ]
  },
  { "title": "Filter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Blocked hostnames",
   "type": "stat",
   "description": "Total number of blocked hostnames set in the filter",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "${subsystem}_blocked_hostnames" }
   ]
  },
  {
   "title": "Blocked IP addresses",
   "type": "stat",
   "description": "Total number of blocked IP addresses set in the filter",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "${subsystem}_blocked_ips" }
   ]
  },
  {
   "title": "Blocked IP prefixes",
   "type": "stat",
   "description": "Total number of blocked IP prefixes (CIDRs) set in the filter",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${subsystem}_blocked_ip_prefixes"
    }
   ]
  },
  {
   "title": "Hostnames filtered per ${period}s",
   "type": "timeseries",
   "description": "Rate per ${period}s of filtered out hostnames by question class and type",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "${period}*sum(rate(${subsystem}_hostnames_filtered[2m])) by (class, type)",
     "legendFormat": "{{class}} {{type}}"
    }
   ]
  },
  {
   "title": "IP addresses filtered per ${period}s",
   "type": "timeseries",
   "description": "Rate per ${period}s of IP addresses filtered out by response type",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "${period}*sum(rate(${subsystem}_ips_filtered[2m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Cache type",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "${subsystem}_cache_labels", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Max entries",
   "type": "stat",
   "description": "Maximum number of entries allowed in the cache",
   "gridPos": { "h": 7, "w": 3, "x": 2, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "${subsystem}_cache_max_entries", "legendFormat": "Max entries" }
   ]
  },
  {
   "title": "Cache capacity used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(${subsystem}_cache_insert - ${subsystem}_cache_remove)/${subsystem}_cache_max_entries"
    }
   ]
  },
  {
   "title": "Cache hit percentage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(${subsystem}_cache_hit[2m]) / (rate(${subsystem}_cache_hit[2m]) + rate(${subsystem}_cache_miss[2m]))"
    }
   ]
  },
  {
   "title": "Cache hit and miss per ${period}s",
   "type": "timeseries",
   "description": "Cache hit and miss per ${period}s with a 2 minutes rate",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "${period}*rate(${subsystem}_cache_hit[2m])",
     "legendFormat": "Hit"
    },
    {
     "expr": "${period}*rate(${subsystem}_cache_miss[2m])",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "Cache hit percentage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(${subsystem}_cache_hit[2m]) / (rate(${subsystem}_cache_hit[2m]) + rate(${subsystem}_cache_miss[2m]))",
     "legendFormat": "Hit percentage"
    }
   ]
  },
  {
   "title": "Cache entries",
   "type": "timeseries",
   "description": "Number of entries present in the cache",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "${subsystem}_cache_insert - ${subsystem}_cache_remove",
     "legendFormat": "Cache size"
    }
   ]
  },
  {
   "title": "Cache internals over ${period}s",
   "type": "timeseries",
   "description": "Cache internals metrics per ${period}s with a 2 minutes rate",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "${period}*rate(${subsystem}_cache_expired[2m])",
     "legendFormat": "Expired"
    },
    {
     "expr": "${period}*rate(${subsystem}_cache_move[2m])",
     "legendFormat": "Move"
    },
    {
     "expr": "${period}*rate(${subsystem}_cache_remove[2m])",
     "legendFormat": "Removed"
    },
    {
     "expr": "${period}*rate(${subsystem}_cache_insert[2m])",
     "legendFormat": "Inserted"
    },
    {
     "expr": "${period}*rate(${subsystem}_cache_insertEmpty[2m])",
     "legendFormat": "Add empty"
    },
    {
     "expr": "${period}*rate(${subsystem}_cache_getEmpty[2m])",
     "legendFormat": "Get empty"
    }
   ]
  }
 ]
}