// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/pkg/doh/metrics (interfaces: Interface)

// Package doh is a generated GoMock package.
package doh

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDoHMetrics is a mock of Interface interface.
type MockDoHMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockDoHMetricsMockRecorder
}

// MockDoHMetricsMockRecorder is the mock recorder for MockDoHMetrics.
type MockDoHMetricsMockRecorder struct {
	mock *MockDoHMetrics
}

// NewMockDoHMetrics creates a new mock instance.
func NewMockDoHMetrics(ctrl *gomock.Controller) *MockDoHMetrics {
	mock := &MockDoHMetrics{ctrl: ctrl}
	mock.recorder = &MockDoHMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDoHMetrics) EXPECT() *MockDoHMetricsMockRecorder {
	return m.recorder
}

// AnswersInc mocks base method.
func (m *MockDoHMetrics) AnswersInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AnswersInc", arg0, arg1)
}

// AnswersInc indicates an expected call of AnswersInc.
func (mr *MockDoHMetricsMockRecorder) AnswersInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswersInc", reflect.TypeOf((*MockDoHMetrics)(nil).AnswersInc), arg0, arg1)
}

// DNSDialInc mocks base method.
func (m *MockDoHMetrics) DNSDialInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DNSDialInc", arg0, arg1)
}

// DNSDialInc indicates an expected call of DNSDialInc.
func (mr *MockDoHMetricsMockRecorder) DNSDialInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DNSDialInc", reflect.TypeOf((*MockDoHMetrics)(nil).DNSDialInc), arg0, arg1)
}

// DoHDialInc mocks base method.
func (m *MockDoHMetrics) DoHDialInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DoHDialInc", arg0)
}

// DoHDialInc indicates an expected call of DoHDialInc.
func (mr *MockDoHMetricsMockRecorder) DoHDialInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoHDialInc", reflect.TypeOf((*MockDoHMetrics)(nil).DoHDialInc), arg0)
}

// DoTDialInc mocks base method.
func (m *MockDoHMetrics) DoTDialInc(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DoTDialInc", arg0, arg1, arg2)
}

// DoTDialInc indicates an expected call of DoTDialInc.
func (mr *MockDoHMetricsMockRecorder) DoTDialInc(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoTDialInc", reflect.TypeOf((*MockDoHMetrics)(nil).DoTDialInc), arg0, arg1, arg2)
}

// InFlightRequestsDec mocks base method.
func (m *MockDoHMetrics) InFlightRequestsDec() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InFlightRequestsDec")
}

// InFlightRequestsDec indicates an expected call of InFlightRequestsDec.
func (mr *MockDoHMetricsMockRecorder) InFlightRequestsDec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InFlightRequestsDec", reflect.TypeOf((*MockDoHMetrics)(nil).InFlightRequestsDec))
}

// InFlightRequestsInc mocks base method.
func (m *MockDoHMetrics) InFlightRequestsInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InFlightRequestsInc")
}

// InFlightRequestsInc indicates an expected call of InFlightRequestsInc.
func (mr *MockDoHMetricsMockRecorder) InFlightRequestsInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InFlightRequestsInc", reflect.TypeOf((*MockDoHMetrics)(nil).InFlightRequestsInc))
}

// QuestionsInc mocks base method.
func (m *MockDoHMetrics) QuestionsInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QuestionsInc", arg0, arg1)
}

// QuestionsInc indicates an expected call of QuestionsInc.
func (mr *MockDoHMetricsMockRecorder) QuestionsInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuestionsInc", reflect.TypeOf((*MockDoHMetrics)(nil).QuestionsInc), arg0, arg1)
}

// RcodeInc mocks base method.
func (m *MockDoHMetrics) RcodeInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RcodeInc", arg0)
}

// RcodeInc indicates an expected call of RcodeInc.
func (mr *MockDoHMetricsMockRecorder) RcodeInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RcodeInc", reflect.TypeOf((*MockDoHMetrics)(nil).RcodeInc), arg0)
}

// RequestsInc mocks base method.
func (m *MockDoHMetrics) RequestsInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RequestsInc")
}

// RequestsInc indicates an expected call of RequestsInc.
func (mr *MockDoHMetricsMockRecorder) RequestsInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestsInc", reflect.TypeOf((*MockDoHMetrics)(nil).RequestsInc))
}

// ResponsesInc mocks base method.
func (m *MockDoHMetrics) ResponsesInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResponsesInc")
}

// ResponsesInc indicates an expected call of ResponsesInc.
func (mr *MockDoHMetricsMockRecorder) ResponsesInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponsesInc", reflect.TypeOf((*MockDoHMetrics)(nil).ResponsesInc))
}
