// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/v2/pkg/doh/metrics (interfaces: DialMetrics)

// Package doh is a generated GoMock package.
package doh

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDoHMetrics is a mock of DialMetrics interface.
type MockDoHMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockDoHMetricsMockRecorder
}

// MockDoHMetricsMockRecorder is the mock recorder for MockDoHMetrics.
type MockDoHMetricsMockRecorder struct {
	mock *MockDoHMetrics
}

// NewMockDoHMetrics creates a new mock instance.
func NewMockDoHMetrics(ctrl *gomock.Controller) *MockDoHMetrics {
	mock := &MockDoHMetrics{ctrl: ctrl}
	mock.recorder = &MockDoHMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDoHMetrics) EXPECT() *MockDoHMetricsMockRecorder {
	return m.recorder
}

// DNSDialInc mocks base method.
func (m *MockDoHMetrics) DNSDialInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DNSDialInc", arg0, arg1)
}

// DNSDialInc indicates an expected call of DNSDialInc.
func (mr *MockDoHMetricsMockRecorder) DNSDialInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DNSDialInc", reflect.TypeOf((*MockDoHMetrics)(nil).DNSDialInc), arg0, arg1)
}

// DoHDialInc mocks base method.
func (m *MockDoHMetrics) DoHDialInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DoHDialInc", arg0)
}

// DoHDialInc indicates an expected call of DoHDialInc.
func (mr *MockDoHMetricsMockRecorder) DoHDialInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoHDialInc", reflect.TypeOf((*MockDoHMetrics)(nil).DoHDialInc), arg0)
}

// DoTDialInc mocks base method.
func (m *MockDoHMetrics) DoTDialInc(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DoTDialInc", arg0, arg1, arg2)
}

// DoTDialInc indicates an expected call of DoTDialInc.
func (mr *MockDoHMetricsMockRecorder) DoTDialInc(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoTDialInc", reflect.TypeOf((*MockDoHMetrics)(nil).DoTDialInc), arg0, arg1, arg2)
}
