// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/v2/pkg/middlewares/filter/mapfilter (interfaces: Metrics,Logger)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=mapfilter . Metrics,Logger
//

// Package mapfilter is a generated GoMock package.
package mapfilter

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// HostnamesFilteredInc mocks base method.
func (m *MockMetrics) HostnamesFilteredInc(qClass, qType string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HostnamesFilteredInc", qClass, qType)
}

// HostnamesFilteredInc indicates an expected call of HostnamesFilteredInc.
func (mr *MockMetricsMockRecorder) HostnamesFilteredInc(qClass, qType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HostnamesFilteredInc", reflect.TypeOf((*MockMetrics)(nil).HostnamesFilteredInc), qClass, qType)
}

// IPsFilteredInc mocks base method.
func (m *MockMetrics) IPsFilteredInc(rrtype string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IPsFilteredInc", rrtype)
}

// IPsFilteredInc indicates an expected call of IPsFilteredInc.
func (mr *MockMetricsMockRecorder) IPsFilteredInc(rrtype any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IPsFilteredInc", reflect.TypeOf((*MockMetrics)(nil).IPsFilteredInc), rrtype)
}

// SetBlockedHostnames mocks base method.
func (m *MockMetrics) SetBlockedHostnames(n int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBlockedHostnames", n)
}

// SetBlockedHostnames indicates an expected call of SetBlockedHostnames.
func (mr *MockMetricsMockRecorder) SetBlockedHostnames(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlockedHostnames", reflect.TypeOf((*MockMetrics)(nil).SetBlockedHostnames), n)
}

// SetBlockedIPPrefixes mocks base method.
func (m *MockMetrics) SetBlockedIPPrefixes(n int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBlockedIPPrefixes", n)
}

// SetBlockedIPPrefixes indicates an expected call of SetBlockedIPPrefixes.
func (mr *MockMetricsMockRecorder) SetBlockedIPPrefixes(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlockedIPPrefixes", reflect.TypeOf((*MockMetrics)(nil).SetBlockedIPPrefixes), n)
}

// SetBlockedIPs mocks base method.
func (m *MockMetrics) SetBlockedIPs(n int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBlockedIPs", n)
}

// SetBlockedIPs indicates an expected call of SetBlockedIPs.
func (mr *MockMetricsMockRecorder) SetBlockedIPs(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlockedIPs", reflect.TypeOf((*MockMetrics)(nil).SetBlockedIPs), n)
}

// SetFqdnExemptFromRebindingProtection mocks base method.
func (m *MockMetrics) SetFqdnExemptFromRebindingProtection(n int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFqdnExemptFromRebindingProtection", n)
}

// SetFqdnExemptFromRebindingProtection indicates an expected call of SetFqdnExemptFromRebindingProtection.
func (mr *MockMetricsMockRecorder) SetFqdnExemptFromRebindingProtection(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFqdnExemptFromRebindingProtection", reflect.TypeOf((*MockMetrics)(nil).SetFqdnExemptFromRebindingProtection), n)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Log mocks base method.
func (m *MockLogger) Log(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Log", s)
}

// Log indicates an expected call of Log.
func (mr *MockLoggerMockRecorder) Log(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockLogger)(nil).Log), s)
}
