// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/v2/internal/exchanger (interfaces: PoolMetrics,Warner)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=exchanger . PoolMetrics,Warner
//

// Package exchanger is a generated GoMock package.
package exchanger

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockPoolMetrics is a mock of PoolMetrics interface.
type MockPoolMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockPoolMetricsMockRecorder
	isgomock struct{}
}

// MockPoolMetricsMockRecorder is the mock recorder for MockPoolMetrics.
type MockPoolMetricsMockRecorder struct {
	mock *MockPoolMetrics
}

// NewMockPoolMetrics creates a new mock instance.
func NewMockPoolMetrics(ctrl *gomock.Controller) *MockPoolMetrics {
	mock := &MockPoolMetrics{ctrl: ctrl}
	mock.recorder = &MockPoolMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoolMetrics) EXPECT() *MockPoolMetricsMockRecorder {
	return m.recorder
}

// DeadConnInc mocks base method.
func (m *MockPoolMetrics) DeadConnInc(address string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeadConnInc", address)
}

// DeadConnInc indicates an expected call of DeadConnInc.
func (mr *MockPoolMetricsMockRecorder) DeadConnInc(address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeadConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).DeadConnInc), address)
}

// GetConnInc mocks base method.
func (m *MockPoolMetrics) GetConnInc(address, outcome string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetConnInc", address, outcome)
}

// GetConnInc indicates an expected call of GetConnInc.
func (mr *MockPoolMetricsMockRecorder) GetConnInc(address, outcome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).GetConnInc), address, outcome)
}

// LiveConnInc mocks base method.
func (m *MockPoolMetrics) LiveConnInc(address string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LiveConnInc", address)
}

// LiveConnInc indicates an expected call of LiveConnInc.
func (mr *MockPoolMetricsMockRecorder) LiveConnInc(address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).LiveConnInc), address)
}

// NewConnsInc mocks base method.
func (m *MockPoolMetrics) NewConnsInc(address, outcome string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NewConnsInc", address, outcome)
}

// NewConnsInc indicates an expected call of NewConnsInc.
func (mr *MockPoolMetricsMockRecorder) NewConnsInc(address, outcome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConnsInc", reflect.TypeOf((*MockPoolMetrics)(nil).NewConnsInc), address, outcome)
}

// PutConnInc mocks base method.
func (m *MockPoolMetrics) PutConnInc(address, state string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PutConnInc", address, state)
}

// PutConnInc indicates an expected call of PutConnInc.
func (mr *MockPoolMetricsMockRecorder) PutConnInc(address, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).PutConnInc), address, state)
}

// RecordLifetime mocks base method.
func (m *MockPoolMetrics) RecordLifetime(address string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordLifetime", address, duration)
}

// RecordLifetime indicates an expected call of RecordLifetime.
func (mr *MockPoolMetricsMockRecorder) RecordLifetime(address, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordLifetime", reflect.TypeOf((*MockPoolMetrics)(nil).RecordLifetime), address, duration)
}

// RecordUseTime mocks base method.
func (m *MockPoolMetrics) RecordUseTime(address string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordUseTime", address, duration)
}

// RecordUseTime indicates an expected call of RecordUseTime.
func (mr *MockPoolMetricsMockRecorder) RecordUseTime(address, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordUseTime", reflect.TypeOf((*MockPoolMetrics)(nil).RecordUseTime), address, duration)
}

// RemovedConnsAdd mocks base method.
func (m *MockPoolMetrics) RemovedConnsAdd(address string, removed uint) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemovedConnsAdd", address, removed)
}

// RemovedConnsAdd indicates an expected call of RemovedConnsAdd.
func (mr *MockPoolMetricsMockRecorder) RemovedConnsAdd(address, removed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovedConnsAdd", reflect.TypeOf((*MockPoolMetrics)(nil).RemovedConnsAdd), address, removed)
}

// RenewConnInc mocks base method.
func (m *MockPoolMetrics) RenewConnInc(address, reason, outcome string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenewConnInc", address, reason, outcome)
}

// RenewConnInc indicates an expected call of RenewConnInc.
func (mr *MockPoolMetricsMockRecorder) RenewConnInc(address, reason, outcome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).RenewConnInc), address, reason, outcome)
}

// MockWarner is a mock of Warner interface.
type MockWarner struct {
	ctrl     *gomock.Controller
	recorder *MockWarnerMockRecorder
	isgomock struct{}
}

// MockWarnerMockRecorder is the mock recorder for MockWarner.
type MockWarnerMockRecorder struct {
	mock *MockWarner
}

// NewMockWarner creates a new mock instance.
func NewMockWarner(ctrl *gomock.Controller) *MockWarner {
	mock := &MockWarner{ctrl: ctrl}
	mock.recorder = &MockWarnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarner) EXPECT() *MockWarnerMockRecorder {
	return m.recorder
}

// Warn mocks base method.
func (m *MockWarner) Warn(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", s)
}

// Warn indicates an expected call of Warn.
func (mr *MockWarnerMockRecorder) Warn(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockWarner)(nil).Warn), s)
}
