// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/v2/internal/exchanger (interfaces: PoolMetrics,Warner)

// Package exchanger is a generated GoMock package.
package exchanger

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockPoolMetrics is a mock of PoolMetrics interface.
type MockPoolMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockPoolMetricsMockRecorder
}

// MockPoolMetricsMockRecorder is the mock recorder for MockPoolMetrics.
type MockPoolMetricsMockRecorder struct {
	mock *MockPoolMetrics
}

// NewMockPoolMetrics creates a new mock instance.
func NewMockPoolMetrics(ctrl *gomock.Controller) *MockPoolMetrics {
	mock := &MockPoolMetrics{ctrl: ctrl}
	mock.recorder = &MockPoolMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoolMetrics) EXPECT() *MockPoolMetricsMockRecorder {
	return m.recorder
}

// DeadConnInc mocks base method.
func (m *MockPoolMetrics) DeadConnInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeadConnInc", arg0)
}

// DeadConnInc indicates an expected call of DeadConnInc.
func (mr *MockPoolMetricsMockRecorder) DeadConnInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeadConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).DeadConnInc), arg0)
}

// GetConnInc mocks base method.
func (m *MockPoolMetrics) GetConnInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetConnInc", arg0, arg1)
}

// GetConnInc indicates an expected call of GetConnInc.
func (mr *MockPoolMetricsMockRecorder) GetConnInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).GetConnInc), arg0, arg1)
}

// LiveConnInc mocks base method.
func (m *MockPoolMetrics) LiveConnInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LiveConnInc", arg0)
}

// LiveConnInc indicates an expected call of LiveConnInc.
func (mr *MockPoolMetricsMockRecorder) LiveConnInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).LiveConnInc), arg0)
}

// NewConnsInc mocks base method.
func (m *MockPoolMetrics) NewConnsInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NewConnsInc", arg0, arg1)
}

// NewConnsInc indicates an expected call of NewConnsInc.
func (mr *MockPoolMetricsMockRecorder) NewConnsInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConnsInc", reflect.TypeOf((*MockPoolMetrics)(nil).NewConnsInc), arg0, arg1)
}

// PutConnInc mocks base method.
func (m *MockPoolMetrics) PutConnInc(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PutConnInc", arg0, arg1)
}

// PutConnInc indicates an expected call of PutConnInc.
func (mr *MockPoolMetricsMockRecorder) PutConnInc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).PutConnInc), arg0, arg1)
}

// RecordUseTime mocks base method.
func (m *MockPoolMetrics) RecordUseTime(arg0 string, arg1 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordUseTime", arg0, arg1)
}

// RecordUseTime indicates an expected call of RecordUseTime.
func (mr *MockPoolMetricsMockRecorder) RecordUseTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordUseTime", reflect.TypeOf((*MockPoolMetrics)(nil).RecordUseTime), arg0, arg1)
}

// RemovedConnsAdd mocks base method.
func (m *MockPoolMetrics) RemovedConnsAdd(arg0 string, arg1 uint) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemovedConnsAdd", arg0, arg1)
}

// RemovedConnsAdd indicates an expected call of RemovedConnsAdd.
func (mr *MockPoolMetricsMockRecorder) RemovedConnsAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovedConnsAdd", reflect.TypeOf((*MockPoolMetrics)(nil).RemovedConnsAdd), arg0, arg1)
}

// RenewConnInc mocks base method.
func (m *MockPoolMetrics) RenewConnInc(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenewConnInc", arg0, arg1, arg2)
}

// RenewConnInc indicates an expected call of RenewConnInc.
func (mr *MockPoolMetricsMockRecorder) RenewConnInc(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewConnInc", reflect.TypeOf((*MockPoolMetrics)(nil).RenewConnInc), arg0, arg1, arg2)
}

// MockWarner is a mock of Warner interface.
type MockWarner struct {
	ctrl     *gomock.Controller
	recorder *MockWarnerMockRecorder
}

// MockWarnerMockRecorder is the mock recorder for MockWarner.
type MockWarnerMockRecorder struct {
	mock *MockWarner
}

// NewMockWarner creates a new mock instance.
func NewMockWarner(ctrl *gomock.Controller) *MockWarner {
	mock := &MockWarner{ctrl: ctrl}
	mock.recorder = &MockWarnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarner) EXPECT() *MockWarnerMockRecorder {
	return m.recorder
}

// Warn mocks base method.
func (m *MockWarner) Warn(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", arg0)
}

// Warn indicates an expected call of Warn.
func (mr *MockWarnerMockRecorder) Warn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockWarner)(nil).Warn), arg0)
}
