// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/dns/v2/internal/exchanger (interfaces: PoolMetrics,Warner)

// Package exchanger is a generated GoMock package.
package exchanger

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPoolMetrics is a mock of PoolMetrics interface.
type MockPoolMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockPoolMetricsMockRecorder
}

// MockPoolMetricsMockRecorder is the mock recorder for MockPoolMetrics.
type MockPoolMetricsMockRecorder struct {
	mock *MockPoolMetrics
}

// NewMockPoolMetrics creates a new mock instance.
func NewMockPoolMetrics(ctrl *gomock.Controller) *MockPoolMetrics {
	mock := &MockPoolMetrics{ctrl: ctrl}
	mock.recorder = &MockPoolMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoolMetrics) EXPECT() *MockPoolMetricsMockRecorder {
	return m.recorder
}

// ConnsAdd mocks base method.
func (m *MockPoolMetrics) ConnsAdd(arg0 string, arg1 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConnsAdd", arg0, arg1)
}

// ConnsAdd indicates an expected call of ConnsAdd.
func (mr *MockPoolMetricsMockRecorder) ConnsAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnsAdd", reflect.TypeOf((*MockPoolMetrics)(nil).ConnsAdd), arg0, arg1)
}

// InUseConnsAdd mocks base method.
func (m *MockPoolMetrics) InUseConnsAdd(arg0 string, arg1 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InUseConnsAdd", arg0, arg1)
}

// InUseConnsAdd indicates an expected call of InUseConnsAdd.
func (mr *MockPoolMetricsMockRecorder) InUseConnsAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InUseConnsAdd", reflect.TypeOf((*MockPoolMetrics)(nil).InUseConnsAdd), arg0, arg1)
}

// LiveConnsAdd mocks base method.
func (m *MockPoolMetrics) LiveConnsAdd(arg0 string, arg1 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LiveConnsAdd", arg0, arg1)
}

// LiveConnsAdd indicates an expected call of LiveConnsAdd.
func (mr *MockPoolMetricsMockRecorder) LiveConnsAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveConnsAdd", reflect.TypeOf((*MockPoolMetrics)(nil).LiveConnsAdd), arg0, arg1)
}

// RenewRequestsInc mocks base method.
func (m *MockPoolMetrics) RenewRequestsInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenewRequestsInc", arg0)
}

// RenewRequestsInc indicates an expected call of RenewRequestsInc.
func (mr *MockPoolMetricsMockRecorder) RenewRequestsInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewRequestsInc", reflect.TypeOf((*MockPoolMetrics)(nil).RenewRequestsInc), arg0)
}

// RenewalsInc mocks base method.
func (m *MockPoolMetrics) RenewalsInc(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenewalsInc", arg0)
}

// RenewalsInc indicates an expected call of RenewalsInc.
func (mr *MockPoolMetricsMockRecorder) RenewalsInc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewalsInc", reflect.TypeOf((*MockPoolMetrics)(nil).RenewalsInc), arg0)
}

// MockWarner is a mock of Warner interface.
type MockWarner struct {
	ctrl     *gomock.Controller
	recorder *MockWarnerMockRecorder
}

// MockWarnerMockRecorder is the mock recorder for MockWarner.
type MockWarnerMockRecorder struct {
	mock *MockWarner
}

// NewMockWarner creates a new mock instance.
func NewMockWarner(ctrl *gomock.Controller) *MockWarner {
	mock := &MockWarner{ctrl: ctrl}
	mock.recorder = &MockWarnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarner) EXPECT() *MockWarnerMockRecorder {
	return m.recorder
}

// Warn mocks base method.
func (m *MockWarner) Warn(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", arg0)
}

// Warn indicates an expected call of Warn.
func (mr *MockWarnerMockRecorder) Warn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockWarner)(nil).Warn), arg0)
}
