name: Markdown
on:
  push:
    branches: [master]
    paths:
      - README.md
      - .github/workflows/markdown.yml
jobs:
  markdown:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: peter-evans/dockerhub-description@v3
        if: github.repository == 'qdm12/dns' && github.event_name == 'push'
        with:
          username: qmcgaw
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: qmcgaw/dns
          short-description: DNS over TLS upstream server connected to DNS over TLS (IPv4 and IPv6) servers
          readme-filepath: README.md
