name: Docker Hub description
on:
  push:
    branches: [master]
    paths:
      - README.md
      - .github/workflows/markdown.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.4.1
        with:
          username: qmcgaw
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: qmcgaw/dns
          short-description: DNS over TLS upstream server connected to DNS over TLS (IPv4 and IPv6) servers
          readme-filepath: README.md
